Repository boostcampwm-2022/web20-OAO, pull requests merged in 2022-12, with the labels that each got.

#157 FIX: remote server todos path proxy 설정
  client/default.conf
Labels: bug

#158 FEAT: tablerowheader 및 modal에 todo id copy button 추가
  client/src/components/todos/TableRowHeader.tsx
  client/src/container/todos/Table.tsx
  client/src/container/todos/TableModal.tsx
  client/src/images/Copy.svg
  client/src/util/Common.ts
Labels: feature

#160 feat: todo modal로 create/edit시 until의 시간 지정 구현
  client/src/components/todos/LabeledInput.tsx
  client/src/container/todos/TableModal.tsx
  client/src/util/Common.ts
  client/src/util/Constants.ts
Labels: feature

#163 FEAT: 테이블 뷰 정렬 및 필터링 구현
  client/src/components/Button.tsx
  client/src/components/Text.tsx
  client/src/components/main/PostponeBox.tsx
  client/src/components/todos/FilterBox.tsx
  client/src/components/todos/SortBox.tsx
  client/src/components/todos/TableHeader.tsx
  client/src/container/todos/Table.tsx
  client/src/core/todo/todoList.ts
  client/src/core/todo/todoList.type.ts
  client/src/core/todo/todoList.util.ts
Labels: feature

#164 FIX: todo prev/next modal input값 공백 및 줄바꿈 삭제 및 uuid 형식 검증
  client/src/components/todos/LabeledInput.tsx
  client/src/container/todos/TableModal.tsx
  client/src/util/Constants.ts
Labels: bug

#165 FIX: elapsed time 0으로 초기화되는 버그 수정
  client/src/components/main/PostponeBox.tsx
  client/src/components/main/TodoInteractionButton.tsx
  client/src/components/main/TodoTimeText.tsx
  client/src/container/Menubar.tsx
  client/src/container/main/TodoStatus.tsx
  client/src/container/main/TodoTimeInteraction.tsx
  client/src/core/todo/todoList.ts
  client/src/hooks/useActiveTodo.tsx
  client/src/hooks/useButtonConfig.tsx
  client/src/hooks/useDone.tsx
  client/src/hooks/useElapsedTime.tsx
  client/src/hooks/usePostpone.tsx
  client/src/hooks/useTodoList.tsx
  client/src/page/Main.tsx
Labels: bug

#172 chore: 자동완성 이용시 절대경로 완성
  client/tsconfig.json
Labels: feature

#181 FEAT: elapsed time 전역 상태로 수정
  client/src/App.tsx
  client/src/components/main/PostponeBox.tsx
  client/src/components/main/TodoInteractionButton.tsx
  client/src/components/main/TodoTimeText.tsx
  client/src/container/main/TodoContents.tsx
  client/src/container/main/TodoStatus.tsx
  client/src/container/main/TodoTimeInteraction.tsx
  client/src/container/main/TodoTitle.tsx
  client/src/container/todos/TableModal.tsx
  client/src/hooks/useActiveTodo.tsx
  client/src/hooks/useButtonConfig.tsx
  client/src/hooks/useDone.ts
  client/src/hooks/useDone.tsx
  client/src/hooks/useElapsedTime.tsx
  client/src/hooks/usePostpone.ts
  client/src/hooks/usePostpone.tsx
  client/src/hooks/useTodoList.tsx
  client/src/page/Main.tsx
  client/src/page/Todos.tsx
  client/src/util/Common.ts
  client/src/util/GlobalState.ts
  client/tsconfig.json
  client/vite.config.ts
Labels: bug, feature

#189 FEAT: 다이어그램 뷰 구현
  client/src/App.tsx
  client/src/components/diagram/TodoBlock.tsx
  client/src/components/diagram/TodoVertex.tsx
  client/src/container/Menubar.tsx
  client/src/container/diagram/Diagram.tsx
  client/src/container/diagram/DiagramFrame.tsx
  client/src/container/diagram/DiagramHeader.tsx
  client/src/container/todos/Table.tsx
  client/src/core/todo/todoList.ts
  client/src/core/todo/todoList.type.ts
  client/src/core/todo/todoList.util.ts
  client/src/images/Diagram.svg
  client/src/images/Planning.svg
  client/src/page/DiagramPage.tsx
  client/src/util/Constants.ts
  client/src/util/GlobalStyle.tsx
  client/src/util/diagram.util.ts
  client/src/util/queue.ts
  client/src/util/wrapPromise.ts
Labels: feature

#193 FEAT: main page todo 없는 상황 handling
  client/src/images/Celebrate.svg
  client/src/page/Main.tsx
Labels: feature

#197 fix: 튜토리얼 중입니다 글씨의 글씨체, 사이즈, 색깔 수정
  client/src/App.tsx
Labels: bug

#199 FEAT: main page 커피 연기 애니메이션 추가
  client/src/container/main/TodoStatus.tsx
  client/src/images/Relaxing.tsx
Labels: feature

#200 fix: 튜토리얼 중 새로고침 시 redirection 기능 추가
  client/src/App.tsx
  client/src/util/GlobalState.ts
Labels: bug

#198 FEAT: 자동완성 SearchBar 구현 및 TableModal과 연결
  client/src/components/SearchBar.tsx
  client/src/components/todos/LabeledInput.tsx
  client/src/components/todos/RelatedTodoInput.tsx
  client/src/components/todos/TableRowHeader.tsx
  client/src/container/todos/TableModal.tsx
  client/src/core/todo/todoList.ts
  client/src/images/Search.svg
  client/src/util/Common.ts
  client/src/util/Constants.ts
Labels: feature

#215 FEAT: 다이어그램 뷰 고도화
  client/index.html
  client/src/components/Bubble.tsx
  client/src/components/ElapsedTimeText.tsx
  client/src/components/ToggleButton.tsx
  client/src/components/diagram/DiagramControlPanel.tsx
  client/src/components/diagram/ErrorBubble.tsx
  client/src/components/diagram/PopUp.tsx
  client/src/components/diagram/TodoBlock.tsx
  client/src/components/diagram/TodoBlockPopUp.tsx
  client/src/components/diagram/TodoVertex.tsx
  client/src/components/diagram/TodoVertexPopUp.tsx
  client/src/components/diagram/WarningBubble.tsx
  client/src/container/Menubar.tsx
  client/src/container/TodoController.tsx
  client/src/container/diagram/Diagram.tsx
  client/src/container/diagram/DiagramFrame.tsx
  client/src/container/diagram/DiagramHeader.tsx
  client/src/images/Error.svg
  client/src/images/Path.svg
  client/src/images/Warning.svg
  client/src/page/DiagramPage.tsx
  client/src/util/GlobalStyle.tsx
  client/src/util/diagram.util.ts
Labels: feature

#221 FIX: todo간 순환참조 예외 처리
  client/src/components/diagram/TodoVertexPopUp.tsx
  client/src/container/todos/TableModal.tsx
  client/src/core/todo/todoList.ts
Labels: bug

#227 FEAT: modal component 분리
  client/index.html
  client/src/App.tsx
  client/src/components/Modal.tsx
  client/src/components/OverLay.tsx
  client/src/components/todos/LabeledInput.tsx
  client/src/components/todos/TableHeader.tsx
  client/src/components/todos/TableRow.tsx
  client/src/components/todos/TableRowDetail.tsx
  client/src/components/todos/TableRowHeader.tsx
  client/src/container/CreateModal.tsx
  client/src/container/EditModal.tsx
  client/src/container/Menubar.tsx
  client/src/container/TodoController.tsx
  client/src/container/todos/Table.tsx
  client/src/container/todos/TableModal.tsx
  client/src/container/todos/TodosHeader.tsx
  client/src/hooks/useModalComplete.ts
  client/src/page/DiagramPage.tsx
  client/src/page/Main.tsx
  client/src/page/Todos.tsx
  client/src/util/Constants.ts
  client/src/util/GlobalStyle.tsx
  client/src/util/modal.util.ts
Labels: feature

#228 FEAT: SearchBar 컴포넌트 분리 및 keyboard 이벤트 추가
  client/src/components/Modal.tsx
  client/src/components/Search.tsx
  client/src/components/SearchBar.tsx
  client/src/components/SearchListContent.tsx
  client/src/components/main/TodoInteractionButton.tsx
  client/src/components/todos/LabeledInput.tsx
  client/src/components/todos/RelatedTodoInput.tsx
  client/src/components/todos/TableRowDetail.tsx
  client/src/components/todos/TableRowHeader.tsx
  client/src/container/EditModal.tsx
  client/src/hooks/useModalComplete.ts
  client/src/util/Constants.ts
  client/src/util/GlobalState.ts
Labels: feature

#231 FIX: elapsed time 버그 수정 및 불필요한 전역상태 제거
  client/src/components/main/TodoTimeText.tsx
  client/src/container/TodoController.tsx
  client/src/page/Main.tsx
  client/src/util/GlobalState.ts
Labels: bug

#232 FEAT: 다이어그램 뷰 2차 고도화
  client/src/components/Modal.tsx
  client/src/components/diagram/NewTodoVertex.tsx
  client/src/components/diagram/TodoBlock.tsx
  client/src/components/diagram/TodoBlockPopUp.tsx
  client/src/components/diagram/TodoVertex.tsx
  client/src/container/diagram/Diagram.tsx
  client/src/container/diagram/DiagramFrame.tsx
  client/src/container/diagram/DiagramHeader.tsx
  client/src/hooks/useDiagramAnimation.ts
  client/src/page/DiagramPage.tsx
  client/src/util/diagram.util.ts
Labels: feature

#234 FIX: searchbar에서 특수문자 검색창 입력 안되게 처리
  client/src/components/Search.tsx
  client/src/components/SearchBar.tsx
  client/src/components/SearchListContent.tsx
  client/src/components/todos/LabeledInput.tsx
  client/src/components/todos/RelatedTodoInput.tsx
  client/src/hooks/useModalComplete.ts
Labels: bug

#236 FEAT: 필터링 복수 선택 기능 및 뷰에서의 상태 표시 세분화
  client/src/components/diagram/TodoBlock.tsx
  client/src/components/todos/FilterBox.tsx
  client/src/components/todos/SortBox.tsx
  client/src/components/todos/TableHeader.tsx
  client/src/components/todos/TableRowHeader.tsx
  client/src/container/todos/Table.tsx
  client/src/images/ColoredDone.svg
  client/src/images/ColoredPostponed.svg
  client/src/images/ColoredReady.svg
  client/src/images/ColoredWait.svg
  client/src/util/todos.util.ts
Labels: feature

#245 FIX: 다이어그램 뷰의 위상정렬이 특정 상황에 제대로 이루어지 않는 버그
  client/src/util/diagram.util.ts
Labels: bug

#246 FIX: 제목 overflow ellipsis로 수정
  client/src/container/TodoController.tsx
Labels: bug

#249 FIX: todoList.edit을 호출할 때 변경사항이 있는 property만 보내도록 수정
  client/src/util/todos.util.ts
Labels: bug

#250 FEAT: table 뷰 elapsed time 보이게 수정 및 time interaction 개선
  client/src/components/StartPauseButton.tsx
  client/src/components/main/TodoInteractionButton.tsx
  client/src/components/todos/TableRowDetail.tsx
  client/src/container/TodoController.tsx
  client/src/hooks/useModalComplete.ts
  client/src/util/Common.ts
  client/src/util/GlobalState.ts
  client/src/util/modal.util.ts
Labels: feature

#255 FIX: modal 제대로 동작하지 않는 오류 수정
  client/src/hooks/useModalComplete.ts
  client/src/util/modal.util.ts
Labels: bug

#267 FEAT: favicon 추가 및 스타일 디테일링
  client/index.html
  client/public/android-icon-144x144.png
  client/public/android-icon-192x192.png
  client/public/android-icon-36x36.png
  client/public/android-icon-48x48.png
  client/public/android-icon-72x72.png
  client/public/android-icon-96x96.png
  client/public/apple-icon-114x114.png
  client/public/apple-icon-120x120.png
  client/public/apple-icon-144x144.png
  client/public/apple-icon-152x152.png
  client/public/apple-icon-180x180.png
  client/public/apple-icon-57x57.png
  client/public/apple-icon-60x60.png
  client/public/apple-icon-72x72.png
  client/public/apple-icon-76x76.png
  client/public/apple-icon-precomposed.png
  client/public/apple-icon.png
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon-96x96.png
  client/public/favicon.ico
  client/public/manifest.json
  client/public/ms-icon-144x144.png
  client/public/ms-icon-150x150.png
  client/public/ms-icon-310x310.png
  client/public/ms-icon-70x70.png
  client/src/App.tsx
  client/src/components/tutorial/TutorialVideo.tsx
  client/src/container/Header.tsx
Labels: feature

#268 RELEASE: favicon 업데이트
  client/index.html
  client/public/android-icon-144x144.png
  client/public/android-icon-192x192.png
  client/public/android-icon-36x36.png
  client/public/android-icon-48x48.png
  client/public/android-icon-72x72.png
  client/public/android-icon-96x96.png
  client/public/apple-icon-114x114.png
  client/public/apple-icon-120x120.png
  client/public/apple-icon-144x144.png
  client/public/apple-icon-152x152.png
  client/public/apple-icon-180x180.png
  client/public/apple-icon-57x57.png
  client/public/apple-icon-60x60.png
  client/public/apple-icon-72x72.png
  client/public/apple-icon-76x76.png
  client/public/apple-icon-precomposed.png
  client/public/apple-icon.png
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon-96x96.png
  client/public/favicon.ico
  client/public/manifest.json
  client/public/ms-icon-144x144.png
  client/public/ms-icon-150x150.png
  client/public/ms-icon-310x310.png
  client/public/ms-icon-70x70.png
  client/src/App.tsx
  client/src/components/tutorial/TutorialVideo.tsx
  client/src/container/Header.tsx
Labels: release
