Repository boostcampwm-2022/web20-OAO, pull requests merged in 2022-11, with the labels that each got.

#7 feat: project 생성
  client/.eslintrc.cjs
  client/.gitignore
  client/.prettierrc.cjs
  client/index.html
  client/package.json
  client/src/App.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  client/yarn.lock
Labels: 🛠 환경설정

#11 FEAT: jest 설정
  client/jest.config.cjs
  client/package.json
  client/tsconfig.json
  client/yarn.lock
Labels: 🛠 환경설정

#19 FEAT: 이슈템플릿 이슈 폼 형태로 변환
  .github/ISSUE_TEMPLATE/Bug-Report.yml
  .github/ISSUE_TEMPLATE/Feature.yml
  .github/ISSUE_TEMPLATE/Micro-Feature.yml
  .github/ISSUE_TEMPLATE/버그-리포트.md
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/pull-request-template.md
Labels: feature

#46 ENV: docker 및 client build github action 등록
  .github/actions/slack-notify/action.yml
  .github/workflows/CLIENT_BUILD.yml
  .github/workflows/CLIENT_DEV_BUILD.yml
  .github/workflows/PRODUCTION_RELEASE.yml
  .github/workflows/SERVER_BUILD.yml
  .github/workflows/SERVER_DEV_BUILD.yml
  .github/workflows/TEST_COVERAGE.yml
  README.md
  client/Dockerfile
  client/default.conf
  client/src/App.tsx
  docker-compose.yml
  nginx/Dockerfile
  nginx/default.conf
  server/Dockerfile
  server/index.ts
  server/package.json
  server/tsconfig.json
Labels: 🛠 환경설정

#70 fix: airbnb eslint에서 standard eslint로 변경
  client/.eslintrc.cjs
  client/package.json
  client/src/core/todo/index.ts
  client/src/core/todo/test/generator.ts
  client/src/core/todo/test/sort.test.ts
  client/src/core/todo/test/type.ts
  client/src/core/todo/test/update.test.ts
  client/src/core/todo/test/validator.ts
  client/yarn.lock
Labels: bug

#88 FEAT: todolist 클래스 구현
  .gitignore
  client/reports/jest-junit.xml
  client/src/core/todo/index.ts
  client/src/core/todo/test/generator.ts
  client/src/core/todo/test/sort.data.json
  client/src/core/todo/test/sort.test.ts
  client/src/core/todo/test/type.ts
  client/src/core/todo/test/update.test.ts
  client/src/core/todo/test/validator.test.ts
  client/src/core/todo/test/validator.ts
  client/src/core/todo/todoList.ts
Labels: feature

#105 FEAT: Todolist CRUD 및 타입 인터페이스 리팩터링
  client/src/core/todo/test/generator.ts
  client/src/core/todo/test/sort.test.ts
  client/src/core/todo/test/update.test.ts
  client/src/core/todo/test/validator.test.ts
  client/src/core/todo/test/validator.ts
  client/src/core/todo/todoList.ts
Labels: feature

#107 FEAT: main component 개발
  client/package.json
  client/src/App.tsx
  client/src/components/Button.tsx
  client/src/components/Image.tsx
  client/src/components/LoginButton.tsx
  client/src/components/PostponeBox.tsx
  client/src/components/Text.tsx
  client/src/components/TodoInteractionButton.tsx
  client/src/components/TodoTimeText.tsx
  client/src/container/Header.tsx
  client/src/container/Menubar.tsx
  client/src/container/TodoContents.tsx
  client/src/container/TodoStatus.tsx
  client/src/container/TodoTimeInteraction.tsx
  client/src/container/TodoTitle.tsx
  client/src/core/todo/index.ts
  client/src/core/todo/todoList.ts
  client/src/hooks/useButtonConfig.tsx
  client/src/hooks/useDone.tsx
  client/src/hooks/useElapsedTime.tsx
  client/src/hooks/useTodoList.tsx
  client/src/images/Done.svg
  client/src/images/DropDown.svg
  client/src/images/Home.svg
  client/src/images/LongLogo.svg
  client/src/images/Postpone.svg
  client/src/images/Relaxing.svg
  client/src/images/Start.svg
  client/src/images/Table.svg
  client/src/images/Working.svg
  client/src/images/pause.svg
  client/src/index.css
  client/src/main.tsx
  client/src/page/Main.tsx
  client/src/util/Common.ts
  client/src/util/Constants.ts
  client/src/util/GlobalState.ts
  client/src/util/GlobalStyle.tsx
  client/tsconfig.json
  client/vite.config.ts
  client/yarn.lock
Labels: feature

#109 FIX: dev client ci/cd build fail 해결
  .github/workflows/CLIENT_DEV_BUILD.yml
  client/src/images/Pause.svg
Labels: bug

#130 FEAT: DB interface 분리 및 주입 & IndexedDB CRUD 구현
  client/jest.config.cjs
  client/package.json
  client/src/core/repository/repository.indexedDB.ts
  client/src/core/repository/repository.interface.ts
  client/src/core/repository/repository.memoryDB.ts
  client/src/core/todo/index.ts
  client/src/core/todo/test/generator.ts
  client/src/core/todo/test/sort.test.ts
  client/src/core/todo/test/update.test.ts
  client/src/core/todo/test/validator.test.ts
  client/src/core/todo/test/validator.ts
  client/src/core/todo/todo.ts
  client/src/core/todo/todo.type.ts
  client/src/core/todo/todo.util.ts
  client/src/core/todo/todoList.interface.ts
  client/src/core/todo/todoList.ts
  client/src/core/todo/todoList.util.ts
  client/tsconfig.json
  client/vite.config.ts
  client/yarn.lock
Labels: feature

#132 FEAT: table page 구현
  client/src/App.tsx
  client/src/components/OverLay.tsx
  client/src/components/Select.tsx
  client/src/components/Text.tsx
  client/src/components/main/PostponeBox.tsx
  client/src/components/main/TodoInteractionButton.tsx
  client/src/components/main/TodoTimeText.tsx
  client/src/components/todos/LabeledInput.tsx
  client/src/components/todos/TableHeader.tsx
  client/src/components/todos/TableRow.tsx
  client/src/components/todos/TableRowDetail.tsx
  client/src/components/todos/TableRowHeader.tsx
  client/src/components/todos/TodoTitleList.tsx
  client/src/container/Header.tsx
  client/src/container/Menubar.tsx
  client/src/container/main/TodoContents.tsx
  client/src/container/main/TodoStatus.tsx
  client/src/container/main/TodoTimeInteraction.tsx
  client/src/container/main/TodoTitle.tsx
  client/src/container/todos/Table.tsx
  client/src/container/todos/TableModal.tsx
  client/src/container/todos/TodosHeader.tsx
  client/src/core/repository/repository.indexedDB.ts
  client/src/core/todo/todo.ts
  client/src/core/todo/todoList.ts
  client/src/hooks/useTodoList.tsx
  client/src/images/Checked.svg
  client/src/images/Create.svg
  client/src/images/Delete.svg
  client/src/images/Unchecked.svg
  client/src/images/Update.svg
  client/src/images/Waiting.svg
  client/src/main.tsx
  client/src/page/Main.tsx
  client/src/page/Todos.tsx
  client/src/util/Common.ts
  client/src/util/Constants.ts
  client/src/util/GlobalState.ts
Labels: feature

#134 FIX: vite top level await 가능하도록 esNext target으로 변경
  client/vite.config.ts
Labels: bug

#138 FIX: oldTodo의 next Todo들이 다시 oldTodo에만 접근할 수 있는 문제 해결
  client/src/core/todo/todoList.ts
Labels: bug

#141 FIX: 잠시 미루기 기능 시 Todo 상태 업데이트 되지 않는 문제 해결
  client/src/core/todo/todoList.ts
Labels: bug

#142 RELEASE: 잠시 미루기 버그 수정
  client/src/core/todo/todoList.ts
Labels: release
